BancoRenisson.App/Pages/Index.cshtml.cs
using BancoRenisson.Domain.ContasCorrentes;
using BancoRenisson.Domain.ContasCorrentes.Repositories;
using BancoRenisson.Domain.Movimentacoes;
using BancoRenisson.Domain.Movimentacoes.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BancoRenisson.App.Pages
{
    public class IndextModel : PageModel
    {
        private readonly ICurrentAccountRepository _currentAccountRepository;
        private readonly IMovementRepository _movementRepository;
        private readonly ILogger<IndextModel> _logger;

        public IndextModel(
            ILogger<IndextModel> logger,
            ICurrentAccountRepository currentAccountRepository,
            IMovementRepository movementRepository)
        {
            _logger = logger;
            _currentAccountRepository = currentAccountRepository;
            _movementRepository = movementRepository;
        }

        public IEnumerable<CurrentAccount> Currents { get; set; }
        public IEnumerable<Movement> Movements { get; private set; }
        public CurrentAccount _current { get; set; }

        [BindProperty()]
        public CurrentAccount Current { get; set; }

        [BindProperty()]
        public Movement Movement { get; set; }

        public async Task OnGet()
        {
            Currents = await _currentAccountRepository.GetAll();
            Movements = await _movementRepository.GetAll();
        }

        public async Task<IActionResult> OnPostOpenAccount()
        {
            if (string.IsNullOrEmpty(Current.UserName))
            {
                ModelState.AddModelError("Preencha o nome do titular", "O nome do titular é obrigatorio para abrir contas.");
                await OnGet();

                return Page();
            }

            await _currentAccountRepository.Add(Current);
            await OnGet();

            return Page();
        }

        public async Task<IActionResult> OnPostDeposit()
        {
            if (!ValidatorOperations() || await CurrentAccount())
            {
                await OnGet();

                return Page();
            }

            Movement.CurrentAccountId = _current.Id;
            Movement.CurrentAccount = _current;
            Movement.Deposit(Movement.ValueMovement);
            await _movementRepository.Add(Movement);
            await _currentAccountRepository.Update(Movement.CurrentAccount);

            await OnGet();

            return Page();
        }

        public async Task<IActionResult> OnPostWithdraw()
        {
            if (!ValidatorOperations() || await CurrentAccount())
            {
                await OnGet();

                return Page();
            }

            Movement.CurrentAccountId = _current.Id;
            Movement.CurrentAccount = _current;

            var result = Movement.Withdraw(Movement.ValueMovement);

            if (!result)
            {
                ModelState.AddModelError("Saldo insuficiente", "Não há saldo disponível para realizar a operação");
                await OnGet();

                return Page();
            }

            await _movementRepository.Add(Movement);
            await _currentAccountRepository.Update(Movement.CurrentAccount);
            await OnGet();

            return Page();
        }

        public async Task<IActionResult> OnPostPayment()
        {
            if (!ValidatorOperations(true) || await CurrentAccount())
            {
                await OnGet();

                return Page();
            }

            Movement.CurrentAccountId = _current.Id;
            Movement.CurrentAccount = _current;

            var result = Movement.Payment(Movement.ValueMovement, Movement.Description);

            if (!result)
            {
                ModelState.AddModelError("Saldo insuficiente", "Não há saldo dísponivel para realizar a operação");
                await OnGet();

                return Page();
            }

            await _movementRepository.Add(Movement);
            await _currentAccountRepository.Update(Movement.CurrentAccount);

            await OnGet();

            return Page();
        }

        private async Task<bool> CurrentAccount()
        {
            _current = await _currentAccountRepository.SearchByNumber(Current.NumberAccount);

            if (_current is null)
            {
                ModelState.AddModelError("Conta não localizada", "O número da conta digitado não foi encontrado.");
                return true;
            }
            return false;
        }

        private bool ValidatorOperations(bool pay = false)
        {
            if (Current.NumberAccount <= 0)
            {
                ModelState.AddModelError("Preencha o número da conta", "Número da conta é obrigatorio.");
                return false;
            }

            if (Movement.ValueMovement <= 0)
            {
                ModelState.AddModelError("Preencha o valor", "Valor é obrigatorio.");
                return false;
            }

            if (pay && string.IsNullOrEmpty(Movement.Description))
            {
                ModelState.AddModelError("Preencha a Descrição", "Descrição é obrigatorio para pagamentos.");
                return false;
            }

            return true;
        }
    }
}

BancoRenisson.App/Pages/Index.cshtml
@page
@model IndextModel
@{
    ViewData["Title"] = "Desafio Warren Renisson";
}
<h1>@ViewData["Title"]</h1>

<div style="color: red">
    @Html.ValidationSummary()
</div>

<form method="post">
    <br />
    <br />
    <h3 style="text-align:center" class="display-5">Abertura de Conta</h3>

    <div class="input-group col-md-10">
        <input type="text" asp-for="Current.UserName" class="form-control" placeholder="Nome Do titular" aria-label="Username" aria-describedby="basic-addon1">
        <button style="margin-left: 5px" asp-page-handler="OpenAccount" type="submit" class="btn btn-info create">Abrir Conta Corrente<i class="glyphicon glyphicon-open"></i></button>
    </div>
</form>
<br />
<form method="post">
    <h3 style="text-align:center" class="display-5">Operações da conta</h3>

    <div class="input-group col-md-10">
        <input style="margin: 5px" type="number" asp-for="Current.NumberAccount" step="1" min="1" class="form-control" placeholder="Número Da Conta" aria-label="Username" aria-describedby="basic-addon1">
        <div style="margin: 5px" class="input-group-prepend">
            <span class="input-group-text">R$</span>
            <input type="number" styler="margin-top:5px" min="0.01" asp-for="Movement.ValueMovement" placeholder="Valor da operação" step="0.010" data-number-to-fixed="2" data-number-stepfactor="100" class="form-control currency" id="c2" />
        </div>
    </div>

    <div class="input-group col-md-9">
        <input style="margin: 5px" type="text" asp-for="Movement.Description" class="form-control" placeholder="Descrição do Pagamento" aria-label="Description" aria-describedby="basic-addon1">
        <button asp-page-handler="Deposit" type="submit" class="btn btn-success create">Depositar<i class="glyphicon glyphicon-open"></i></button>
        <button style="margin-left: 10px" asp-page-handler="Withdraw" type="submit" class="btn btn-danger create">Sacar<i class="glyphicon glyphicon-open"></i></button>
        <button style="margin-left: 10px" asp-page-handler="Payment" type="submit" class="btn btn-warning create">Pagar<i class="glyphicon glyphicon-open"></i></button>
    </div>
</form>
<br />
<h3 style="text-align:center" class="display-5">Contas Abertas</h3>
<br />
<table class="table">
    <tr>
        <th>@Html.DisplayName("Número da conta")</th>
        <th>@Html.DisplayName("Nome do titular")</th>
        <th>@Html.DisplayName("Saldo R$")</th>
        <th>@Html.DisplayName("Data da abertura")</th>
        <th>@Html.DisplayName("Data da ultima movimentação")</th>
        <th></th>
    </tr>
    @foreach (var item in Model.Currents.OrderBy(x => x.NumberAccount))
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.NumberAccount)</td>
            <td>@Html.DisplayFor(modelItem => item.UserName)</td>
            <td>@Html.DisplayFor(modelItem => item.Value)</td>
            <td>@Html.DisplayFor(modelItem => item.DateCreation)</td>
            <td>@Html.DisplayFor(modelItem => item.DateLastUpdate)</td>
        </tr>
    }
</table>
<br />
<h3 style="text-align:center" class="display-5">Ultimas Movimentações</h3>
<br />

<table class="table">
    <tr>
        <th>@Html.DisplayName("Data da operação")</th>
        <th>@Html.DisplayName("Operação")</th>
        <th>@Html.DisplayName("Número da conta")</th>
        <th>@Html.DisplayName("Valor R$")</th>
        <th>@Html.DisplayName("Descrição")</th>
        <th></th>
    </tr>
    @foreach (var item in Model.Movements.OrderByDescending(x => x.DateCreation))
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.DateCreation)</td>
            <td>@Html.DisplayFor(modelItem => item.OperationDescription)</td>
            <td>@Html.DisplayFor(modelItem => item.CurrentAccount.NumberAccount)</td>
            <td>@Html.DisplayFor(modelItem => item.ValueMovement)</td>
            <td>@Html.DisplayFor(modelItem => item.Description)</td>
        </tr>
    }
</table>

BancoRenisson.App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BancoRenisson.App - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>